namef=input("Enter First Name: ")
namel=input("Enter Last Name: ")
namem=input("Enter Middle Name: ")
birth=input("Enter Birthday: ")
gen=input("What Gender are you?: ")
add=input("What's your address?: ")
course=input("What course do you study?: ")
year=input("What year level are you?: ")
print("First Name:", namef)
print("Last Name:", namel)
print("Middle Name:", namem)
print("Birth:", birth)
print("Gender:", gen)
print("Address:", add)
print("Course:", course)
print("Year Level:", year)